version: '2'
services:
  web:
    build: ./
    container_name: the_enmore_inn_web
    labels:
        - "traefik.frontend.rule=Host:test.theenmoreinn.com"
        - "traefik.port=80"
    networks:
        - proxy
networks:
  proxy:
